development:
     adapter: mysql
     encoding: utf8
     reconnect: false
     database: NRIROR
     pool: 5
     username: root
     password: root
     socket: /tmp/mysql.sock
     port: 3306	 
production:
    adapter: mysql
    database: NRIROR
    pool: 5
    timeout: 5000
    host: localhost 
    username: root
    password: root
    port: 3306	
test:
    adapter: mysql
    database: NRIROR
    pool: 5
    timeout: 5000
    host: localhost 
    username: root
    password: root


