# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7261e078850ef6a2a947cd60f2a9205a1db2657e86c8c853d0f7a5f19e53fb9c20f690571c7a176641011beabcc2f3375fc9a0a2f0fd1ef4913116a839e4a9ee

test:
  secret_key_base: b38185867a13f632d3381808a9693d36e2affcb02fe201dd396caaf9515f520c522b9f4d48e4714620a216ec7a3457bfb3a9140de3decbaf5d6a357397c1589a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
